// Compact emoji dataset for the picker: categories with [emoji, keywords].
// English-only keywords, intentionally brief (lightweight).
window.__yqaEmojiData = [
  {
    icon: '😀', name: 'Smileys',
    emojis: [
      ['😀', 'grin smile happy laugh'], ['😁', 'beam teeth grin'], ['😂', 'joy tears laugh lol'],
      ['🤣', 'rofl rolling laugh'], ['😃', 'happy open smile'], ['😄', 'happy laugh'], ['😅', 'sweat laugh relief'],
      ['😆', 'laugh squint'], ['😉', 'wink'], ['😊', 'blush smile warm'], ['😍', 'love heart eyes'],
      ['🤩', 'star struck excited'], ['😘', 'kiss'], ['😎', 'cool sunglasses'], ['🤓', 'nerd glasses'],
      ['🧐', 'monocle inspect'], ['🤔', 'think thinking hmm'], ['🤨', 'skeptic eyebrow'],
      ['😐', 'neutral meh'], ['😴', 'sleep tired zzz'], ['🤯', 'mindblown explode'], ['😱', 'scream shock'],
      ['🥳', 'party celebrate'], ['😇', 'angel halo innocent'], ['🙃', 'upside down irony'], ['😬', 'grimace awkward'],
      ['🥲', 'tear smile bittersweet'], ['😭', 'cry sob'], ['😤', 'huff frustrated'], ['😡', 'angry mad rage'],
      ['🤗', 'hug'], ['🤫', 'shush quiet secret'], ['🤑', 'money rich dollar'], ['🥶', 'cold freezing'],
      ['🥵', 'hot sweating'], ['😷', 'mask sick'], ['🤖', 'robot bot ai'], ['👻', 'ghost'],
      ['💀', 'skull dead'], ['👽', 'alien ufo'], ['🤡', 'clown'], ['💩', 'poop'],
    ],
  },
  {
    icon: '👋', name: 'Gestures & People',
    emojis: [
      ['👋', 'wave hello hi hand'], ['👍', 'thumbs up like good'], ['👎', 'thumbs down dislike'],
      ['👏', 'clap applause'], ['🙌', 'raised hands celebrate'], ['🙏', 'thanks pray please'], ['🤝', 'handshake deal'],
      ['💪', 'muscle strong gym fitness'], ['👉', 'point right'], ['👈', 'point left'], ['👆', 'point up'],
      ['👇', 'point down'], ['✌️', 'peace victory'], ['🤞', 'fingers crossed luck'], ['🤟', 'love you sign'],
      ['🤘', 'rock metal horns'], ['👌', 'ok perfect'], ['🤌', 'pinched chef italian'], ['✊', 'fist'],
      ['✍️', 'writing note'], ['🫶', 'heart hands'], ['👀', 'eyes look watch'], ['🧠', 'brain think smart'],
      ['👨‍💻', 'developer programmer coding man'], ['👩‍💻', 'developer programmer coding woman'],
      ['🧑‍🏫', 'teacher explain tutorial'], ['🧑‍🍳', 'chef cook cooking'], ['🏃', 'run running sport'],
      ['🧘', 'yoga meditation calm'], ['💃', 'dance party'], ['👶', 'baby child'], ['👪', 'family'],
      ['🦸', 'superhero hero'], ['🕵️', 'detective spy search'], ['👑', 'crown king queen'],
    ],
  },
  {
    icon: '🐶', name: 'Animals & Nature',
    emojis: [
      ['🐶', 'dog puppy'], ['🐱', 'cat kitten'], ['🐭', 'mouse'], ['🐹', 'hamster'], ['🐰', 'rabbit bunny'],
      ['🦊', 'fox'], ['🐻', 'bear'], ['🐼', 'panda'], ['🐨', 'koala'], ['🦁', 'lion'],
      ['🐯', 'tiger'], ['🐮', 'cow'], ['🐷', 'pig'], ['🐸', 'frog'], ['🐵', 'monkey'],
      ['🐔', 'chicken rooster'], ['🐧', 'penguin'], ['🦅', 'eagle bird'], ['🦉', 'owl'], ['🦄', 'unicorn'],
      ['🐝', 'bee'], ['🦋', 'butterfly'], ['🐢', 'turtle slow'], ['🐍', 'snake python'],
      ['🐙', 'octopus'], ['🦈', 'shark'], ['🐳', 'whale'], ['🐬', 'dolphin'], ['🐟', 'fish fishing'],
      ['🌱', 'plant sprout grow'], ['🌲', 'tree forest pine'], ['🌴', 'palm vacation tropical'], ['🌵', 'cactus'],
      ['🍀', 'clover luck lucky'], ['🌸', 'blossom cherry flower'], ['🌹', 'rose flower'], ['🌻', 'sunflower'],
      ['🌍', 'earth world globe'], ['🌙', 'moon night'], ['⭐', 'star favorite'], ['🌈', 'rainbow'],
      ['⚡', 'lightning energy fast bolt'], ['🔥', 'fire hot trending flame'], ['❄️', 'snow winter cold'],
      ['🌊', 'wave ocean water surf'], ['☀️', 'sun summer'], ['🌧️', 'rain weather'],
    ],
  },
  {
    icon: '🍕', name: 'Food & Drink',
    emojis: [
      ['🍕', 'pizza'], ['🍔', 'burger'], ['🍟', 'fries'], ['🌭', 'hotdog'], ['🌮', 'taco'],
      ['🍣', 'sushi'], ['🍜', 'ramen noodles soup'], ['🍝', 'pasta spaghetti'], ['🥗', 'salad healthy'],
      ['🥑', 'avocado'], ['🍎', 'apple fruit'], ['🍌', 'banana'], ['🍓', 'strawberry'], ['🍉', 'watermelon'],
      ['🍇', 'grapes wine'], ['🍒', 'cherries'], ['🥕', 'carrot vegetable'], ['🌽', 'corn'],
      ['🍞', 'bread baking'], ['🧀', 'cheese'], ['🥩', 'steak meat bbq grill'], ['🍗', 'chicken drumstick'],
      ['🍳', 'egg cooking breakfast'], ['🥞', 'pancakes'], ['🍰', 'cake baking dessert'],
      ['🧁', 'cupcake muffin'], ['🍪', 'cookie'], ['🍩', 'donut'], ['🍫', 'chocolate'],
      ['🍿', 'popcorn movie cinema'], ['🍦', 'ice cream'], ['🍯', 'honey'], ['☕', 'coffee'],
      ['🍵', 'tea green'], ['🥤', 'drink cup soda'], ['🧃', 'juice'], ['🍺', 'beer'], ['🍷', 'wine'],
      ['🍸', 'cocktail'], ['🥂', 'cheers champagne celebrate'],
    ],
  },
  {
    icon: '⚽', name: 'Activities & Sports',
    emojis: [
      ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🏈', 'american football'], ['🎾', 'tennis'],
      ['🏐', 'volleyball'], ['🏓', 'ping pong table tennis'], ['🏸', 'badminton'], ['🥊', 'boxing fight'],
      ['🥋', 'martial arts judo karate'], ['⛳', 'golf'], ['🏹', 'archery target'], ['🎣', 'fishing'],
      ['🏊', 'swimming'], ['🚴', 'cycling bike'], ['🧗', 'climbing bouldering'], ['🏋️', 'weights gym fitness lifting'],
      ['🤸', 'gymnastics'], ['⛷️', 'ski winter'], ['🏂', 'snowboard'], ['🛹', 'skateboard'],
      ['🏆', 'trophy win winner champion'], ['🥇', 'gold medal first'], ['🎯', 'target dart focus goal'],
      ['🎮', 'gaming controller games'], ['🕹️', 'joystick arcade retro'], ['🎲', 'dice game'],
      ['♟️', 'chess'], ['🧩', 'puzzle'], ['🎳', 'bowling'], ['🎪', 'circus'],
      ['🎤', 'microphone singing podcast karaoke'], ['🎧', 'headphones music listening'], ['🎸', 'guitar rock'],
      ['🎹', 'piano keyboard'], ['🥁', 'drums'], ['🎻', 'violin'], ['🎬', 'movie film clapper video'],
      ['🎨', 'art paint palette design'], ['🎭', 'theater drama'], ['🎵', 'music note'], ['🎶', 'music notes'],
    ],
  },
  {
    icon: '🚗', name: 'Travel & Places',
    emojis: [
      ['🚗', 'car driving'], ['🚕', 'taxi'], ['🚌', 'bus'], ['🚚', 'truck delivery'],
      ['🏎️', 'race car formula fast'], ['🏍️', 'motorcycle'], ['🚲', 'bicycle bike'], ['🛴', 'scooter'],
      ['🚂', 'train locomotive railway'], ['✈️', 'airplane flight travel'], ['🚀', 'rocket launch space startup'],
      ['🛸', 'ufo'], ['🚁', 'helicopter'], ['⛵', 'sailboat'], ['🚢', 'ship cruise'],
      ['⚓', 'anchor harbor'], ['🗺️', 'map travel'], ['🧭', 'compass direction'], ['🏔️', 'mountain peak hiking'],
      ['🏕️', 'camping tent outdoor'], ['🏖️', 'beach vacation'], ['🏝️', 'island'], ['🏜️', 'desert'],
      ['🌋', 'volcano'], ['🏠', 'house home'], ['🏢', 'office building company'], ['🏗️', 'construction crane building'],
      ['🏭', 'factory industry'], ['🏥', 'hospital doctor'], ['🏦', 'bank money'], ['🏫', 'school'],
      ['⛪', 'church'], ['🕌', 'mosque'], ['🗽', 'statue liberty new york usa'], ['🗼', 'tower paris eiffel'],
      ['🏰', 'castle'], ['🎡', 'ferris wheel fair'], ['🌉', 'bridge night'], ['🌆', 'city skyline'],
    ],
  },
  {
    icon: '💡', name: 'Objects & Tech',
    emojis: [
      ['💡', 'idea lightbulb tip'], ['🔦', 'flashlight'], ['🕯️', 'candle'], ['🔌', 'plug power'],
      ['🔋', 'battery energy charge'], ['💻', 'laptop computer coding'], ['🖥️', 'desktop monitor pc'],
      ['⌨️', 'keyboard typing'], ['🖱️', 'mouse click'], ['🖨️', 'printer'], ['📱', 'phone smartphone app mobile'],
      ['📷', 'camera photo'], ['🎥', 'video camera film shoot'], ['📺', 'tv television'], ['📻', 'radio'],
      ['🎙️', 'microphone podcast recording'], ['⏰', 'alarm clock time'], ['⏱️', 'stopwatch timer'],
      ['🧲', 'magnet'], ['🔧', 'wrench tool repair fix'], ['🔨', 'hammer build diy'],
      ['🛠️', 'tools crafting workshop'], ['⚙️', 'gear settings tech engineering'], ['🔩', 'bolt screw'],
      ['🧪', 'lab chemistry experiment test'], ['🔬', 'microscope science research'], ['🔭', 'telescope astronomy'],
      ['💊', 'pill medicine health'], ['💉', 'syringe vaccine'], ['🧬', 'dna biology'],
      ['💰', 'money bag cash'], ['💵', 'dollar bill cash'], ['💶', 'euro money'], ['🪙', 'coin crypto'],
      ['📈', 'chart growth stocks up trading'], ['📉', 'chart down loss'], ['📊', 'bar chart stats data analytics'],
      ['🛒', 'shopping cart buy store ecommerce'], ['🎁', 'gift present surprise'], ['📦', 'package box shipping amazon'],
      ['📚', 'books learning reading study'], ['📖', 'book reading'], ['📝', 'note writing memo'], ['✏️', 'pencil'],
      ['📌', 'pin board save'], ['📎', 'paperclip'], ['✂️', 'scissors cut'], ['🗑️', 'trash bin delete'],
      ['🔑', 'key password'], ['🔒', 'lock security private'], ['🛡️', 'shield protection security'],
      ['🧳', 'luggage suitcase travel'], ['👕', 'tshirt clothing fashion'], ['👟', 'sneaker shoes'], ['💎', 'diamond gem value'],
    ],
  },
  {
    icon: '❤️', name: 'Symbols',
    emojis: [
      ['❤️', 'red heart love'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'],
      ['💙', 'blue heart'], ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'],
      ['💔', 'broken heart'], ['💖', 'sparkling heart'], ['💯', 'hundred percent perfect'],
      ['✅', 'check done complete yes'], ['❌', 'cross wrong no'], ['⭕', 'circle'],
      ['❗', 'exclamation important'], ['❓', 'question'], ['⚠️', 'warning caution'],
      ['🚫', 'prohibited stop no'], ['♻️', 'recycle sustainable'], ['✨', 'sparkles new shiny'],
      ['💫', 'dizzy stars'], ['💥', 'boom explosion collision'], ['💤', 'sleep zzz'], ['💬', 'speech bubble chat comment'],
      ['💭', 'thought bubble thinking'], ['🔔', 'bell notification subscribe'], ['📣', 'megaphone announcement marketing'],
      ['🔍', 'magnifier search seo'], ['🔗', 'link chain'], ['♾️', 'infinity'], ['⏳', 'hourglass time waiting'],
      ['🆕', 'new'], ['🆓', 'free'], ['🔝', 'top'], ['🔞', 'adults only 18'],
      ['🟢', 'green dot live online'], ['🔴', 'red dot live recording'], ['🟡', 'yellow dot'], ['🔵', 'blue dot'],
      ['1️⃣', 'one number'], ['2️⃣', 'two number'], ['3️⃣', 'three number'], ['4️⃣', 'four number'],
      ['5️⃣', 'five number'], ['#️⃣', 'hashtag'], ['▶️', 'play video start'], ['⏸️', 'pause'],
      ['⏩', 'fast forward'], ['🔁', 'repeat loop'],
    ],
  },
];
